Implement optimized poseidon
datenlord/poseidon-spinalhdl pull request #7
Opened 2022-04-14 08:55 UTC by wengwz

Optimized Poseidon which can reach higher performance has been implemented.

2022-05-08 07:49 UTC, pwang7 requested changes

2022-05-08 07:49 UTC, pwang7 commented on src/main/scala/poseidon/ModularAdder.scala
> +      16
radix = 16

2022-05-27 08:47 UTC, wengwz commented on src/main/scala/poseidon/ModularAdder.scala
> +      16
fixed

2022-06-05 07:18 UTC, pwang7 approved these changes

2022-06-05 07:18 UTC, merged